### ISSUE TITLE
Updated Readme?

### ISSUE THREAD

**Issue by MACscr** [adhawkins/ansible-borgbase#11]
Would really be nice to have an updated readme with some examples and documentation. Im finding doing a manual repo setup and using the BorgBackup Ansible Role to be a bit lacking and requires a lot of manual changes after the fact. Your solution appears to fill some of those gaps, but 100% sure how to use it.

**Comment by adhawkins** [comment]
Not sure how I missed this, sorry.

If you look in the 'initial work' branch, then each module is fully documented in the 'ansible' way, with example. I appreciate that this information should ideally be in the README too, I'll get round to addressing that at some point.

Ideally I'd like to submit this to be included as a standard Ansible module, but that needs a bit more work on my part.

**Comment by adhawkins** [comment]
I have now release an Ansible Galaxy collection containing these modules. They should be fully documented, and relatively easy to install and use.
